name: linting, testing, building
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrgix:
        node-version: [ 17.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        with: npm install
      - name: build production project
        with: npm run build:prod
      - name: build production project
        with: npm run build:prod
      - name: linting typescript
        with: npm run lint:ts
      - name: linting scss
        with: npm run lint:scss
      - name: unit testing
        with: npm run test:unit
